#!/usr/bin/env node

const path = require('path');
const mongodump = require('./mongodump');
const { ensureEnv } = require('./env-helper');

const dumpEnv = {
  dbUri: ensureEnv('ELMU_DB_STAGING_URI'),
  dbName: ensureEnv('ELMU_DB_STAGING_DB_NAME')
};

const dumpDir = path.resolve('.tmp/dump');

(async () => {

  await mongodump.dump({
    uri: dumpEnv.dbUri,
    directory: dumpDir,
    db: dumpEnv.dbName
  });

})();
